### ISSUE TITLE
sometimes text_types _cast function returns a UnicodeDecodeError

### ISSUE THREAD

**Issue by eads** [onyxfish/agate#138]
It seems we have to decode utf-8 strings so that they can be properly re-encoded to UTF-8 by six

**Comment by onyxfish** [comment]
When you have a chance mind sending me an example of this or pasting one in here? It's not entirely clear to me what the path was that led to this error.

**Comment by beckjake** [comment]
I know this is years old, but here's a minimal sample that reliably triggers the bad behavior on python 2.7 but passes on 3.6, with what I assume the author of this issue was seeing:


```
import agate
agate.Table([('！',)], column_names=['a'])
```

Note that the exclamation mark there is not a normal one, but U+FF01 ("FULLWIDTH EXCLAMATION MARK")

On python 3, it will pass. On python 2, it will fail with:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)`

The error is ultimately caused by calling `six.text_type('！')`.
