### ISSUE TITLE
Table.from_json

### ISSUE THREAD

**Issue by rdmurphy** [onyxfish/agate#344]
This crossed my mind when I mentioned GeoJSON in #340 — should `Table` have a `from_json()` function to go along with `from_csv()`?

May help make `agate` more API consumer friendly. It's a little hairier than CSV due to the ability to nest. That fit in the scope of the project?

**Comment by onyxfish** [comment]
Yes, absolutely. I think other than CSV this is probably the only data format I want to support in core. (Both because it's common and because Python has a standard library to support.) csvkit's json convertor probably gets us most of the way there.

https://github.com/onyxfish/csvkit/blob/master/csvkit/convert/js.py

**Comment by onyxfish** [comment]
@r0fls would you like me to assign you this ticket since you've got a start on it in #347?

**Comment by onyxfish** [comment]
Assigned to @r0fls, by way of a label, since apparently you can't assign a ticket [without granting push access](https://github.com/isaacs/github/issues/100).
