### ISSUE TITLE
TableSet.from_json

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/agate#373]

**Comment by nbedi** [comment]
I'm working on implementing this but I'm running into an issue. I'm mimicking the TableSet.from_csv function and tests but my implementation hits an error with column_types.

The current Table.from_json implementation does not take column_types so I just called the function with the path as an argument but I get `ValueError: Not all tables have the same column types!` on initializing the TableSet:

The TableSet.from_csv test passes column_types as an argument even though it is not required. When I tried the test without passing column_types, I got the same error.

When I print the column_types for each table I get this:
```
(<agate.data_types.text.Text object at 0x10bc21e90>, <agate.data_types.number.Number object at 0x10bc21c10>)
(<agate.data_types.text.Text object at 0x10bc26150>, <agate.data_types.number.Number object at 0x10bc21c90>)
(<agate.data_types.text.Text object at 0x10bc263d0>, <agate.data_types.number.Number object at 0x10bc21d10>)
```

The check for column_type equality returns false since the addresses are different. Does an existing implementation need to be adjusted or am I missing something? Thanks!
