### ISSUE TITLE
Need a method to print the structure of the table

### ISSUE THREAD

**Issue by TaurusOlson** [onyxfish/agate#393]
One of the first things I do when I work with data is getting to know them. The information I need to know my data are:
- the dimensions
- the names of the columns and their respective types

I didn't find any method in the tutorial or in the Cookbook that would let me easily do that. 

This issue addresses the 2nd point. What I think would be useful would be method called for example `print_structure`:

```python
>>> purchases.print_structure()
|-------------------------------+---------------|
|  column_names                 | column_types  |
|-------------------------------+---------------|
|  state                        | Text          |
|  county                       | Text          |
|  fips                         | Number        |
|  nsn                          | Text          |
|  item_name                    | Text          |
|  quantity                     | Number        |
|  ui                           | Text          |
|  acquisition_cost             | Number        |
|  total_cost                   | Number        |
|  ship_date                    | DateTime      |
|  federal_supply_category      | Number        |
|  federal_supply_category_name | Text          |
|  federal_supply_class         | Number        |
|  federal_supply_class_name    | Text          |
|-------------------------------+---------------|
```
If you think this feature is interesting I can work on it and submit a pull request.

**Comment by onyxfish** [comment]
It's a good call and it goes well with #389. Before `TypeTester` was the default this sort of introspection never seemed necessary, but it's increasingly the normal way and agate should support it better.

I like the example format you show. I think I might actually want to go ahead and make this the result of `__unicode__` so it's the output of `print(table)` rather than `table.print_structure()`. I've waffled on what the default printed representation of a table should be but I think this fits the bill perfectly.

Would love to see a pull request!

**Comment by TaurusOlson** [comment]
I've just submitted the pull request. I didn't use it as the result of __unicode__, I didn't want to modify `Table` too much. I let you implement __unicode__ and do the modifications if necessary.

**Comment by onyxfish** [comment]
Sure, that's no problem. Thanks!
